Repository rodekruis/IBF-system, pull requests merged in 2025-02, with the labels that each got.

#1962 Add test case and update trigger scenarios
  tests/e2e/Pages/MapComponent.ts
  tests/e2e/Pages/TimelineComponent.ts
  tests/e2e/testData/testData.enum.ts
  tests/e2e/tests/ScenarioTrigger.spec.ts
  tests/e2e/tests/TimelineComponent/TimelineComponentNotClickable.ts
Labels: enhancement, test

#1990 Refactor.remove feature files from repository
  README.md
  features/API-admin-user/Change_password.feature
  features/API-admin-user/Create_new_user.feature
  features/API-admin-user/Log_in.feature
  features/API-admin-user/Update_static_data.feature
  features/API-admin-user/Upload_mock_data.feature
  features/Automatic-processes/Scheduled_processes.feature
  features/IBF-portal-admin-user/Use_dev_menu.feature
  features/IBF-portal-user/Use_login_page.feature
  features/IBF-portal-user/dashboard-page/Change_password.feature
  features/IBF-portal-user/dashboard-page/Use_aggregate_section.feature
  features/IBF-portal-user/dashboard-page/Use_chat_section.feature
  features/IBF-portal-user/dashboard-page/Use_disaster_type_section.feature
  features/IBF-portal-user/dashboard-page/Use_header_section.feature
  features/IBF-portal-user/dashboard-page/Use_layers_section.feature
  features/IBF-portal-user/dashboard-page/Use_map_section.feature
  features/IBF-portal-user/dashboard-page/View_area_of_focus_section.feature
  features/README.md
  features/feature-test-report.xlsx
  tests/e2e/tests/TimelineComponent/TimelineComponentNotClickable.ts
Labels: test

#1989 Feat.change frontend alertthreshold layer
  interfaces/IBF-dashboard/src/app/components/aggregates/aggregates.component.ts
  interfaces/IBF-dashboard/src/app/components/matrix/matrix.component.ts
  interfaces/IBF-dashboard/src/app/mocks/alert-areas.mock.ts
  interfaces/IBF-dashboard/src/app/services/aggregates.service.ts
  interfaces/IBF-dashboard/src/app/services/alert-area.service.ts
  interfaces/IBF-dashboard/src/app/services/map-legend.service.ts
  interfaces/IBF-dashboard/src/app/services/map.service.ts
  interfaces/IBF-dashboard/src/app/types/alert-area.ts
  interfaces/IBF-dashboard/src/app/types/ibf-layer.ts
  services/API-service/src/api/admin-area-dynamic-data/admin-area-dynamic-data.controller.ts
  services/API-service/src/api/admin-area-dynamic-data/admin-area-dynamic-data.service.ts
  services/API-service/src/api/admin-area-dynamic-data/const/alert-level-indicators.const.ts
  services/API-service/src/api/admin-area-dynamic-data/enum/dynamic-indicator.enum.ts
  services/API-service/src/api/admin-area/admin-area.service.ts
  services/API-service/src/api/admin-area/services/event-area.service.ts
  services/API-service/src/api/event/event.controller.ts
  services/API-service/src/api/event/event.service.ts
  services/API-service/src/api/notification/notification-content/notification-content.service.ts
  services/API-service/src/api/typhoon-track/typhoon-track.service.ts
  services/API-service/src/scripts/json/indicator-metadata.json
  services/API-service/src/scripts/json/layer-popup-info.xlsx
  services/API-service/src/scripts/mock-helper.service.ts
  services/API-service/src/scripts/mock.service.ts
  tests/e2e/Pages/MapComponent.ts
  tests/e2e/tests/MapComponent/MapComponentTriggerLayer.ts
  tests/e2e/tests/ScenarioNoTrigger.spec.ts
Labels: warning-32041

#1988 fix: update backend references to alertThreshold
  interfaces/IBF-dashboard/src/app/components/aggregates/aggregates.component.ts
  interfaces/IBF-dashboard/src/app/components/matrix/matrix.component.ts
  interfaces/IBF-dashboard/src/app/mocks/alert-areas.mock.ts
  interfaces/IBF-dashboard/src/app/services/aggregates.service.ts
  interfaces/IBF-dashboard/src/app/services/alert-area.service.ts
  interfaces/IBF-dashboard/src/app/services/api.service.ts
  interfaces/IBF-dashboard/src/app/services/map-legend.service.ts
  interfaces/IBF-dashboard/src/app/services/map.service.ts
  interfaces/IBF-dashboard/src/app/types/alert-area.ts
  interfaces/IBF-dashboard/src/app/types/ibf-layer.ts
  services/API-service/src/api/admin-area-data/dto/upload-admin-area-data.dto.ts
  services/API-service/src/api/admin-area-dynamic-data/admin-area-dynamic-data.controller.ts
  services/API-service/src/api/admin-area-dynamic-data/admin-area-dynamic-data.service.ts
  services/API-service/src/api/admin-area-dynamic-data/const/alert-level-indicators.const.ts
  services/API-service/src/api/admin-area-dynamic-data/dto/upload-admin-area-dynamic-data.dto.ts
  services/API-service/src/api/admin-area-dynamic-data/enum/dynamic-indicator.enum.ts
  services/API-service/src/api/admin-area/admin-area.service.ts
  services/API-service/src/api/admin-area/services/event-area.service.ts
  services/API-service/src/api/event/event.controller.ts
  services/API-service/src/api/event/event.service.ts
  services/API-service/src/api/notification/notification-content/notification-content.service.ts
  services/API-service/src/api/notification/whatsapp/whatsapp.service.ts
  services/API-service/src/api/typhoon-track/typhoon-track.service.ts
  services/API-service/src/scripts/json/indicator-metadata.json
  services/API-service/src/scripts/json/layer-popup-info.xlsx
  services/API-service/src/scripts/mock-helper.service.ts
  services/API-service/src/scripts/mock.service.ts
  tests/e2e/Pages/MapComponent.ts
  tests/e2e/tests/MapComponent/MapComponentTriggerLayer.ts
  tests/e2e/tests/ScenarioNoTrigger.spec.ts
Labels: warning-32041

#1998 refactor: move notification logic into /events/process AB#33720
  services/API-service/module-dependencies.md
  services/API-service/src/api/event/event.controller.ts
  services/API-service/src/api/event/event.service.ts
  services/API-service/src/api/notification/notification-content/notification-content.module.ts
  services/API-service/src/api/notification/notification.controller.ts
  services/API-service/src/api/notification/notification.module.ts
  services/API-service/src/api/notification/notification.service.ts
  services/API-service/src/api/process-pipeline/dto/process-events.dto.ts
  services/API-service/src/api/process-pipeline/process-pipeline.controller.ts
  services/API-service/src/api/process-pipeline/process-pipeline.module.ts
  services/API-service/src/api/process-pipeline/process-pipeline.service.ts
  services/API-service/src/app.module.ts
  services/API-service/src/scripts/mock.service.ts
  services/API-service/src/scripts/scripts.controller.ts
  services/API-service/src/scripts/scripts.module.ts
Labels: warning-32041

#2008 Feat.unclickable timeline
  interfaces/IBF-dashboard/src/app/components/date-button/date-button.component.ts
  interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.ts
  interfaces/IBF-dashboard/src/app/components/event-switcher/event-switcher.component.ts
  interfaces/IBF-dashboard/src/app/components/map/map.component.ts
  interfaces/IBF-dashboard/src/app/components/timeline/timeline.component.html
  interfaces/IBF-dashboard/src/app/components/timeline/timeline.component.scss
  interfaces/IBF-dashboard/src/app/components/timeline/timeline.component.ts
  interfaces/IBF-dashboard/src/app/services/timeline.service.ts
  interfaces/IBF-dashboard/src/app/types/lead-time.ts
  interfaces/IBF-dashboard/src/app/types/timeline-state.ts
  services/API-service/src/api/event/event.service.ts
Labels: warning-32041

#2011 Migrations from testing on prod data
  services/API-service/migration/1740565983568-WarningRefactorToProd.ts
  services/API-service/src/api/admin-area-data/admin-area-data.entity.ts
Labels: warning-32041

#2009 Feat.event speech bubble
  interfaces/IBF-dashboard/src/app/components/chat/chat.component.html
  interfaces/IBF-dashboard/src/app/components/chat/chat.component.ts
  interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.html
  interfaces/IBF-dashboard/src/app/components/event-speech-bubble/event-speech-bubble.component.ts
  interfaces/IBF-dashboard/src/app/models/country.model.ts
  interfaces/IBF-dashboard/src/assets/i18n/en.json
  services/API-service/migration/1740498589278-RenameForecastSource.ts
  services/API-service/src/api/country/country-disaster.entity.ts
  services/API-service/src/api/country/country.service.ts
  services/API-service/src/api/country/dto/add-countries.dto.ts
  services/API-service/src/api/event/event.service.ts
  services/API-service/src/scripts/interfaces/country.interface.ts
  services/API-service/src/scripts/json/countries.json
  tests/integration/helpers/API-service/dto/create-country.dto.ts
Labels: warning-32041

#2010 Feat.remove has eap wording distinction
  interfaces/IBF-dashboard/src/app/components/activation-log-button/activation-log-button.component.html
  interfaces/IBF-dashboard/src/app/components/activation-log-button/activation-log-button.component.ts
  interfaces/IBF-dashboard/src/app/components/chat/chat.component.ts
  interfaces/IBF-dashboard/src/app/components/disaster-type/disaster-type.component.ts
  interfaces/IBF-dashboard/src/app/components/user-state/user-state.component.ts
  interfaces/IBF-dashboard/src/app/pages/dashboard/activation-log/activation.log.page.html
  interfaces/IBF-dashboard/src/app/pages/dashboard/activation-log/activation.log.page.ts
  interfaces/IBF-dashboard/src/app/services/disaster-type.service.ts
  interfaces/IBF-dashboard/src/assets/i18n/en.json
  services/API-service/src/scripts/mock-helper.service.ts
Labels: warning-32041
